/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/applications/{id}": {
    get: operations["getApplicationById"];
    put: operations["createApplication"];
    delete: operations["deleteApplicationById"];
  };
  "/api/v1/applications": {
    get: operations["getApplications"];
    post: operations["updateApplications"];
  };
  "/api/v1/applications/schema": {
    get: operations["getApplicationSchema"];
  };
  "/api/v1/applications/test": {
    post: operations["testApplication"];
  };
  "/api/v1/applications/testall": {
    post: operations["testApplications"];
  };
  "/api/v1/applications/action/{name}": {
    post: operations["doApplicationAction"];
  };
  "/api/v1/appprofile": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["AppProfileResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["AppProfileResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AppProfileResource"];
          "text/json": components["schemas"]["AppProfileResource"];
          "application/*+json": components["schemas"]["AppProfileResource"];
        };
      };
    };
  };
  "/api/v1/appprofile/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["AppProfileResource"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "application/json": { [key: string]: string };
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["AppProfileResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AppProfileResource"];
          "text/json": components["schemas"]["AppProfileResource"];
          "application/*+json": components["schemas"]["AppProfileResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/login": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
    post: {
      parameters: {
        query: {
          returnUrl?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            Username?: string;
            Password?: string;
            RememberMe?: string;
          };
        };
      };
    };
  };
  "/logout": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/backup": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["BackupResource"][];
            "application/json": components["schemas"]["BackupResource"][];
            "text/json": components["schemas"]["BackupResource"][];
          };
        };
      };
    };
  };
  "/api/v1/system/backup/{id}": {
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/backup/restore/{id}": {
    post: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/backup/restore/upload": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/command/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["CommandResource"];
            "application/json": components["schemas"]["CommandResource"];
            "text/json": components["schemas"]["CommandResource"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/command": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["CommandResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["CommandResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CommandResource"];
          "text/json": components["schemas"]["CommandResource"];
          "application/*+json": components["schemas"]["CommandResource"];
        };
      };
    };
  };
  "/api/v1/customfilter/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["CustomFilterResource"];
            "application/json": components["schemas"]["CustomFilterResource"];
            "text/json": components["schemas"]["CustomFilterResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["CustomFilterResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CustomFilterResource"];
          "text/json": components["schemas"]["CustomFilterResource"];
          "application/*+json": components["schemas"]["CustomFilterResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/customfilter": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["CustomFilterResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["CustomFilterResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CustomFilterResource"];
          "text/json": components["schemas"]["CustomFilterResource"];
          "application/*+json": components["schemas"]["CustomFilterResource"];
        };
      };
    };
  };
  "/api/v1/config/development/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["DevelopmentConfigResource"];
            "application/json": components["schemas"]["DevelopmentConfigResource"];
            "text/json": components["schemas"]["DevelopmentConfigResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DevelopmentConfigResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DevelopmentConfigResource"];
          "text/json": components["schemas"]["DevelopmentConfigResource"];
          "application/*+json": components["schemas"]["DevelopmentConfigResource"];
        };
      };
    };
  };
  "/api/v1/config/development": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DevelopmentConfigResource"];
          };
        };
      };
    };
  };
  "/api/v1/downloadclient/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["DownloadClientResource"];
            "application/json": components["schemas"]["DownloadClientResource"];
            "text/json": components["schemas"]["DownloadClientResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DownloadClientResource"];
          "text/json": components["schemas"]["DownloadClientResource"];
          "application/*+json": components["schemas"]["DownloadClientResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/downloadclient": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DownloadClientResource"];
          "text/json": components["schemas"]["DownloadClientResource"];
          "application/*+json": components["schemas"]["DownloadClientResource"];
        };
      };
    };
  };
  "/api/v1/downloadclient/schema": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientResource"][];
          };
        };
      };
    };
  };
  "/api/v1/downloadclient/test": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DownloadClientResource"];
          "text/json": components["schemas"]["DownloadClientResource"];
          "application/*+json": components["schemas"]["DownloadClientResource"];
        };
      };
    };
  };
  "/api/v1/downloadclient/testall": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/downloadclient/action/{name}": {
    post: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DownloadClientResource"];
          "text/json": components["schemas"]["DownloadClientResource"];
          "application/*+json": components["schemas"]["DownloadClientResource"];
        };
      };
    };
  };
  "/api/v1/config/downloadclient/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["DownloadClientConfigResource"];
            "application/json": components["schemas"]["DownloadClientConfigResource"];
            "text/json": components["schemas"]["DownloadClientConfigResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientConfigResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["DownloadClientConfigResource"];
          "text/json": components["schemas"]["DownloadClientConfigResource"];
          "application/*+json": components["schemas"]["DownloadClientConfigResource"];
        };
      };
    };
  };
  "/api/v1/config/downloadclient": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["DownloadClientConfigResource"];
          };
        };
      };
    };
  };
  "/api/v1/filesystem": {
    get: {
      parameters: {
        query: {
          path?: string;
          includeFiles?: boolean;
          allowFoldersWithoutTrailingSlashes?: boolean;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/filesystem/type": {
    get: {
      parameters: {
        query: {
          path?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/health/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HealthResource"];
            "application/json": components["schemas"]["HealthResource"];
            "text/json": components["schemas"]["HealthResource"];
          };
        };
      };
    };
  };
  "/api/v1/health": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResource"][];
          };
        };
      };
    };
  };
  "/api/v1/history": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["HistoryResourcePagingResource"];
          };
        };
      };
    };
  };
  "/api/v1/history/since": {
    get: {
      parameters: {
        query: {
          date?: string;
          eventType?: components["schemas"]["HistoryEventType"];
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["HistoryResource"][];
          };
        };
      };
    };
  };
  "/api/v1/history/indexer": {
    get: {
      parameters: {
        query: {
          indexerId?: number;
          eventType?: components["schemas"]["HistoryEventType"];
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["HistoryResource"][];
          };
        };
      };
    };
  };
  "/api/v1/config/host/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HostConfigResource"];
            "application/json": components["schemas"]["HostConfigResource"];
            "text/json": components["schemas"]["HostConfigResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HostConfigResource"];
            "application/json": components["schemas"]["HostConfigResource"];
            "text/json": components["schemas"]["HostConfigResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["HostConfigResource"];
          "text/json": components["schemas"]["HostConfigResource"];
          "application/*+json": components["schemas"]["HostConfigResource"];
        };
      };
    };
  };
  "/api/v1/config/host": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["HostConfigResource"];
            "application/json": components["schemas"]["HostConfigResource"];
            "text/json": components["schemas"]["HostConfigResource"];
          };
        };
      };
    };
  };
  "/api/v1/indexer/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerResource"];
            "application/json": components["schemas"]["IndexerResource"];
            "text/json": components["schemas"]["IndexerResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerResource"];
          "text/json": components["schemas"]["IndexerResource"];
          "application/*+json": components["schemas"]["IndexerResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexer": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerResource"];
          "text/json": components["schemas"]["IndexerResource"];
          "application/*+json": components["schemas"]["IndexerResource"];
        };
      };
    };
  };
  "/api/v1/indexer/schema": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerResource"][];
          };
        };
      };
    };
  };
  "/api/v1/indexer/test": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerResource"];
          "text/json": components["schemas"]["IndexerResource"];
          "application/*+json": components["schemas"]["IndexerResource"];
        };
      };
    };
  };
  "/api/v1/indexer/testall": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexer/action/{name}": {
    post: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerResource"];
          "text/json": components["schemas"]["IndexerResource"];
          "application/*+json": components["schemas"]["IndexerResource"];
        };
      };
    };
  };
  "/api/v1/indexer/categories": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerCategory"][];
            "application/json": components["schemas"]["IndexerCategory"][];
            "text/json": components["schemas"]["IndexerCategory"][];
          };
        };
      };
    };
  };
  "/api/v1/indexer/editor": {
    put: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerEditorResource"];
          "text/json": components["schemas"]["IndexerEditorResource"];
          "application/*+json": components["schemas"]["IndexerEditorResource"];
        };
      };
    };
    delete: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerEditorResource"];
          "text/json": components["schemas"]["IndexerEditorResource"];
          "application/*+json": components["schemas"]["IndexerEditorResource"];
        };
      };
    };
  };
  "/api/v1/indexerproxy/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerProxyResource"];
            "application/json": components["schemas"]["IndexerProxyResource"];
            "text/json": components["schemas"]["IndexerProxyResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerProxyResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerProxyResource"];
          "text/json": components["schemas"]["IndexerProxyResource"];
          "application/*+json": components["schemas"]["IndexerProxyResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexerproxy": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerProxyResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerProxyResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerProxyResource"];
          "text/json": components["schemas"]["IndexerProxyResource"];
          "application/*+json": components["schemas"]["IndexerProxyResource"];
        };
      };
    };
  };
  "/api/v1/indexerproxy/schema": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["IndexerProxyResource"][];
          };
        };
      };
    };
  };
  "/api/v1/indexerproxy/test": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerProxyResource"];
          "text/json": components["schemas"]["IndexerProxyResource"];
          "application/*+json": components["schemas"]["IndexerProxyResource"];
        };
      };
    };
  };
  "/api/v1/indexerproxy/testall": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexerproxy/action/{name}": {
    post: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["IndexerProxyResource"];
          "text/json": components["schemas"]["IndexerProxyResource"];
          "application/*+json": components["schemas"]["IndexerProxyResource"];
        };
      };
    };
  };
  "/api/v1/indexerstats": {
    get: {
      parameters: {
        query: {
          startDate?: string;
          endDate?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerStatsResource"];
            "application/json": components["schemas"]["IndexerStatsResource"];
            "text/json": components["schemas"]["IndexerStatsResource"];
          };
        };
      };
    };
  };
  "/api/v1/indexerstatus/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerStatusResource"];
            "application/json": components["schemas"]["IndexerStatusResource"];
            "text/json": components["schemas"]["IndexerStatusResource"];
          };
        };
      };
    };
  };
  "/api/v1/indexerstatus": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["IndexerStatusResource"][];
            "application/json": components["schemas"]["IndexerStatusResource"][];
            "text/json": components["schemas"]["IndexerStatusResource"][];
          };
        };
      };
    };
  };
  "/initialize.js": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/language/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LanguageResource"];
            "application/json": components["schemas"]["LanguageResource"];
            "text/json": components["schemas"]["LanguageResource"];
          };
        };
      };
    };
  };
  "/api/v1/language": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["LanguageResource"][];
          };
        };
      };
    };
  };
  "/api/v1/localization": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/log": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LogResourcePagingResource"];
            "application/json": components["schemas"]["LogResourcePagingResource"];
            "text/json": components["schemas"]["LogResourcePagingResource"];
          };
        };
      };
    };
  };
  "/api/v1/log/file": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LogFileResource"][];
            "application/json": components["schemas"]["LogFileResource"][];
            "text/json": components["schemas"]["LogFileResource"][];
          };
        };
      };
    };
  };
  "/api/v1/log/file/{filename}": {
    get: {
      parameters: {
        path: {
          filename: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexer/{id}/newznab": {
    get: {
      parameters: {
        path: {
          id: number;
        };
        query: {
          t?: string;
          q?: string;
          cat?: string;
          imdbid?: string;
          tmdbid?: number;
          extended?: string;
          limit?: number;
          offset?: number;
          rid?: number;
          tvmazeid?: number;
          traktid?: number;
          tvdbid?: number;
          season?: number;
          ep?: string;
          album?: string;
          artist?: string;
          label?: string;
          track?: string;
          year?: number;
          genre?: string;
          author?: string;
          title?: string;
          configured?: string;
          source?: string;
          host?: string;
          server?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/{id}/api": {
    get: {
      parameters: {
        path: {
          id: number;
        };
        query: {
          t?: string;
          q?: string;
          cat?: string;
          imdbid?: string;
          tmdbid?: number;
          extended?: string;
          limit?: number;
          offset?: number;
          rid?: number;
          tvmazeid?: number;
          traktid?: number;
          tvdbid?: number;
          season?: number;
          ep?: string;
          album?: string;
          artist?: string;
          label?: string;
          track?: string;
          year?: number;
          genre?: string;
          author?: string;
          title?: string;
          configured?: string;
          source?: string;
          host?: string;
          server?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/indexer/{id}/download": {
    get: {
      parameters: {
        path: {
          id: number;
        };
        query: {
          link?: string;
          file?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/{id}/download": {
    get: {
      parameters: {
        path: {
          id: number;
        };
        query: {
          link?: string;
          file?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/notification/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["NotificationResource"];
            "application/json": components["schemas"]["NotificationResource"];
            "text/json": components["schemas"]["NotificationResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NotificationResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NotificationResource"];
          "text/json": components["schemas"]["NotificationResource"];
          "application/*+json": components["schemas"]["NotificationResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/notification": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NotificationResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NotificationResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NotificationResource"];
          "text/json": components["schemas"]["NotificationResource"];
          "application/*+json": components["schemas"]["NotificationResource"];
        };
      };
    };
  };
  "/api/v1/notification/schema": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NotificationResource"][];
          };
        };
      };
    };
  };
  "/api/v1/notification/test": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NotificationResource"];
          "text/json": components["schemas"]["NotificationResource"];
          "application/*+json": components["schemas"]["NotificationResource"];
        };
      };
    };
  };
  "/api/v1/notification/testall": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/notification/action/{name}": {
    post: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["NotificationResource"];
          "text/json": components["schemas"]["NotificationResource"];
          "application/*+json": components["schemas"]["NotificationResource"];
        };
      };
    };
  };
  "/api/v1/appprofile/schema": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["AppProfileResource"];
            "application/json": components["schemas"]["AppProfileResource"];
            "text/json": components["schemas"]["AppProfileResource"];
          };
        };
      };
    };
  };
  "/api/v1/search/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ReleaseResource"];
            "application/json": components["schemas"]["ReleaseResource"];
            "text/json": components["schemas"]["ReleaseResource"];
          };
        };
      };
    };
  };
  "/api/v1/search": {
    get: {
      parameters: {
        query: {
          Query?: string;
          Type?: string;
          IndexerIds?: number[];
          Categories?: number[];
          Limit?: number;
          Offset?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ReleaseResource"][];
            "application/json": components["schemas"]["ReleaseResource"][];
            "text/json": components["schemas"]["ReleaseResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ReleaseResource"];
            "application/json": components["schemas"]["ReleaseResource"];
            "text/json": components["schemas"]["ReleaseResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReleaseResource"];
          "text/json": components["schemas"]["ReleaseResource"];
          "application/*+json": components["schemas"]["ReleaseResource"];
        };
      };
    };
  };
  "/api/v1/search/bulk": {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ReleaseResource"];
            "application/json": components["schemas"]["ReleaseResource"];
            "text/json": components["schemas"]["ReleaseResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReleaseResource"][];
          "text/json": components["schemas"]["ReleaseResource"][];
          "application/*+json": components["schemas"]["ReleaseResource"][];
        };
      };
    };
  };
  "/content/{path}": {
    get: {
      parameters: {
        path: {
          path: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/": {
    get: {
      parameters: {
        path: {
          path: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/{path}": {
    get: {
      parameters: {
        path: {
          path: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/status": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/routes": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/routes/duplicate": {
    get: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/shutdown": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/system/restart": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/tag/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagResource"];
            "application/json": components["schemas"]["TagResource"];
            "text/json": components["schemas"]["TagResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagResource"];
            "application/json": components["schemas"]["TagResource"];
            "text/json": components["schemas"]["TagResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TagResource"];
          "text/json": components["schemas"]["TagResource"];
          "application/*+json": components["schemas"]["TagResource"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/api/v1/tag": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagResource"][];
            "application/json": components["schemas"]["TagResource"][];
            "text/json": components["schemas"]["TagResource"][];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagResource"];
            "application/json": components["schemas"]["TagResource"];
            "text/json": components["schemas"]["TagResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["TagResource"];
          "text/json": components["schemas"]["TagResource"];
          "application/*+json": components["schemas"]["TagResource"];
        };
      };
    };
  };
  "/api/v1/tag/detail/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagDetailsResource"];
            "application/json": components["schemas"]["TagDetailsResource"];
            "text/json": components["schemas"]["TagDetailsResource"];
          };
        };
      };
    };
  };
  "/api/v1/tag/detail": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TagDetailsResource"][];
            "application/json": components["schemas"]["TagDetailsResource"][];
            "text/json": components["schemas"]["TagDetailsResource"][];
          };
        };
      };
    };
  };
  "/api/v1/system/task": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TaskResource"][];
            "application/json": components["schemas"]["TaskResource"][];
            "text/json": components["schemas"]["TaskResource"][];
          };
        };
      };
    };
  };
  "/api/v1/system/task/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["TaskResource"];
            "application/json": components["schemas"]["TaskResource"];
            "text/json": components["schemas"]["TaskResource"];
          };
        };
      };
    };
  };
  "/api/v1/config/ui/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UiConfigResource"];
            "application/json": components["schemas"]["UiConfigResource"];
            "text/json": components["schemas"]["UiConfigResource"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["UiConfigResource"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UiConfigResource"];
          "text/json": components["schemas"]["UiConfigResource"];
          "application/*+json": components["schemas"]["UiConfigResource"];
        };
      };
    };
  };
  "/api/v1/config/ui": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["UiConfigResource"];
          };
        };
      };
    };
  };
  "/api/v1/update": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UpdateResource"][];
            "application/json": components["schemas"]["UpdateResource"][];
            "text/json": components["schemas"]["UpdateResource"][];
          };
        };
      };
    };
  };
  "/api/v1/log/file/update": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["LogFileResource"][];
            "application/json": components["schemas"]["LogFileResource"][];
            "text/json": components["schemas"]["LogFileResource"][];
          };
        };
      };
    };
  };
  "/api/v1/log/file/update/{filename}": {
    get: {
      parameters: {
        path: {
          filename: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    AppProfileResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      enableRss?: boolean;
      enableInteractiveSearch?: boolean;
      enableAutomaticSearch?: boolean;
      /** Format: int32 */
      minimumSeeders?: number;
    };
    ApplicationResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      fields?: components["schemas"]["Field"][] | null;
      implementationName?: string | null;
      implementation?: string | null;
      configContract?: string | null;
      infoLink?: string | null;
      message?: components["schemas"]["ProviderMessage"];
      tags?: number[] | null;
      presets?: components["schemas"]["ApplicationResource"][] | null;
      syncLevel?: components["schemas"]["ApplicationSyncLevel"];
      testCommand?: string | null;
    };
    /** @enum {string} */
    ApplicationSyncLevel: "disabled" | "addOnly" | "fullSync";
    /** @enum {string} */
    ApplyTags: "add" | "remove" | "replace";
    /** @enum {string} */
    AuthenticationType: "none" | "basic" | "forms";
    BackupResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      path?: string | null;
      type?: components["schemas"]["BackupType"];
      /** Format: int64 */
      size?: number;
      /** Format: date-time */
      time?: string;
    };
    /** @enum {string} */
    BackupType: "scheduled" | "manual" | "update";
    /** @enum {string} */
    BookSearchParam: "q" | "title" | "author";
    /** @enum {string} */
    CertificateValidationType:
      | "enabled"
      | "disabledForLocalAddresses"
      | "disabled";
    Command: {
      sendUpdatesToClient?: boolean;
      updateScheduledTask?: boolean;
      completionMessage?: string | null;
      requiresDiskAccess?: boolean;
      isExclusive?: boolean;
      isTypeExclusive?: boolean;
      name?: string | null;
      /** Format: date-time */
      lastExecutionTime?: string | null;
      /** Format: date-time */
      lastStartTime?: string | null;
      trigger?: components["schemas"]["CommandTrigger"];
      suppressMessages?: boolean;
      clientUserAgent?: string | null;
    };
    /** @enum {string} */
    CommandPriority: "normal" | "high" | "low";
    CommandResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      commandName?: string | null;
      message?: string | null;
      body?: components["schemas"]["Command"];
      priority?: components["schemas"]["CommandPriority"];
      status?: components["schemas"]["CommandStatus"];
      /** Format: date-time */
      queued?: string;
      /** Format: date-time */
      started?: string | null;
      /** Format: date-time */
      ended?: string | null;
      duration?: components["schemas"]["TimeSpan"];
      exception?: string | null;
      trigger?: components["schemas"]["CommandTrigger"];
      clientUserAgent?: string | null;
      /** Format: date-time */
      stateChangeTime?: string | null;
      sendUpdatesToClient?: boolean;
      updateScheduledTask?: boolean;
      /** Format: date-time */
      lastExecutionTime?: string | null;
    };
    /** @enum {string} */
    CommandStatus:
      | "queued"
      | "started"
      | "completed"
      | "failed"
      | "aborted"
      | "cancelled"
      | "orphaned";
    /** @enum {string} */
    CommandTrigger: "unspecified" | "manual" | "scheduled";
    CustomFilterResource: {
      /** Format: int32 */
      id?: number;
      type?: string | null;
      label?: string | null;
      filters?: { [key: string]: unknown }[] | null;
    };
    DevelopmentConfigResource: {
      /** Format: int32 */
      id?: number;
      consoleLogLevel?: string | null;
      logSql?: boolean;
      logIndexerResponse?: boolean;
      /** Format: int32 */
      logRotate?: number;
      filterSentryEvents?: boolean;
    };
    DownloadClientConfigResource: {
      /** Format: int32 */
      id?: number;
    };
    DownloadClientResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      fields?: components["schemas"]["Field"][] | null;
      implementationName?: string | null;
      implementation?: string | null;
      configContract?: string | null;
      infoLink?: string | null;
      message?: components["schemas"]["ProviderMessage"];
      tags?: number[] | null;
      presets?: components["schemas"]["DownloadClientResource"][] | null;
      enable?: boolean;
      protocol?: components["schemas"]["DownloadProtocol"];
      /** Format: int32 */
      priority?: number;
    };
    /** @enum {string} */
    DownloadProtocol: "unknown" | "usenet" | "torrent";
    Field: {
      /** Format: int32 */
      order?: number;
      name?: string | null;
      label?: string | null;
      unit?: string | null;
      helpText?: string | null;
      helpLink?: string | null;
      value?: unknown | null;
      type?: string | null;
      advanced?: boolean;
      selectOptions?: components["schemas"]["SelectOption"][] | null;
      selectOptionsProviderAction?: string | null;
      section?: string | null;
      hidden?: string | null;
      placeholder?: string | null;
    };
    /** @enum {string} */
    HealthCheckResult: "ok" | "notice" | "warning" | "error";
    HealthResource: {
      /** Format: int32 */
      id?: number;
      source?: string | null;
      type?: components["schemas"]["HealthCheckResult"];
      message?: string | null;
      wikiUrl?: components["schemas"]["HttpUri"];
    };
    /** @enum {string} */
    HistoryEventType:
      | "unknown"
      | "releaseGrabbed"
      | "indexerQuery"
      | "indexerRss"
      | "indexerAuth"
      | "indexerInfo";
    HistoryResource: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      indexerId?: number;
      /** Format: date-time */
      date?: string;
      downloadId?: string | null;
      successful?: boolean;
      eventType?: components["schemas"]["HistoryEventType"];
      data?: { [key: string]: string | null } | null;
    };
    HistoryResourcePagingResource: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      sortKey?: string | null;
      sortDirection?: components["schemas"]["SortDirection"];
      filters?: components["schemas"]["PagingResourceFilter"][] | null;
      /** Format: int32 */
      totalRecords?: number;
      records?: components["schemas"]["HistoryResource"][] | null;
    };
    HostConfigResource: {
      /** Format: int32 */
      id?: number;
      bindAddress?: string | null;
      /** Format: int32 */
      port?: number;
      /** Format: int32 */
      sslPort?: number;
      enableSsl?: boolean;
      launchBrowser?: boolean;
      authenticationMethod?: components["schemas"]["AuthenticationType"];
      analyticsEnabled?: boolean;
      username?: string | null;
      password?: string | null;
      logLevel?: string | null;
      consoleLogLevel?: string | null;
      branch?: string | null;
      apiKey?: string | null;
      sslCertPath?: string | null;
      sslCertPassword?: string | null;
      urlBase?: string | null;
      instanceName?: string | null;
      updateAutomatically?: boolean;
      updateMechanism?: components["schemas"]["UpdateMechanism"];
      updateScriptPath?: string | null;
      proxyEnabled?: boolean;
      proxyType?: components["schemas"]["ProxyType"];
      proxyHostname?: string | null;
      /** Format: int32 */
      proxyPort?: number;
      proxyUsername?: string | null;
      proxyPassword?: string | null;
      proxyBypassFilter?: string | null;
      proxyBypassLocalAddresses?: boolean;
      certificateValidation?: components["schemas"]["CertificateValidationType"];
      backupFolder?: string | null;
      /** Format: int32 */
      backupInterval?: number;
      /** Format: int32 */
      backupRetention?: number;
      /** Format: int32 */
      historyCleanupDays?: number;
    };
    HostStatistics: {
      host?: string | null;
      /** Format: int32 */
      numberOfQueries?: number;
      /** Format: int32 */
      numberOfGrabs?: number;
    };
    HttpUri: {
      fullUri?: string | null;
      scheme?: string | null;
      host?: string | null;
      /** Format: int32 */
      port?: number | null;
      path?: string | null;
      query?: string | null;
      fragment?: string | null;
    };
    IndexerCapabilityResource: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      limitsMax?: number | null;
      /** Format: int32 */
      limitsDefault?: number | null;
      categories?: components["schemas"]["IndexerCategory"][] | null;
      supportsRawSearch?: boolean;
      searchParams?: components["schemas"]["SearchParam"][] | null;
      tvSearchParams?: components["schemas"]["TvSearchParam"][] | null;
      movieSearchParams?: components["schemas"]["MovieSearchParam"][] | null;
      musicSearchParams?: components["schemas"]["MusicSearchParam"][] | null;
      bookSearchParams?: components["schemas"]["BookSearchParam"][] | null;
    };
    IndexerCategory: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
      subCategories?: components["schemas"]["IndexerCategory"][] | null;
    };
    IndexerEditorResource: {
      indexerIds?: number[] | null;
      enable?: string | null;
      /** Format: int32 */
      appProfileId?: number | null;
      tags?: number[] | null;
      applyTags?: components["schemas"]["ApplyTags"];
    };
    /** @enum {string} */
    IndexerPrivacy: "public" | "semiPrivate" | "private";
    IndexerProxyResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      fields?: components["schemas"]["Field"][] | null;
      implementationName?: string | null;
      implementation?: string | null;
      configContract?: string | null;
      infoLink?: string | null;
      message?: components["schemas"]["ProviderMessage"];
      tags?: number[] | null;
      presets?: components["schemas"]["IndexerProxyResource"][] | null;
      link?: string | null;
      onHealthIssue?: boolean;
      supportsOnHealthIssue?: boolean;
      includeHealthWarnings?: boolean;
      testCommand?: string | null;
    };
    IndexerResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      fields?: components["schemas"]["Field"][] | null;
      implementationName?: string | null;
      implementation?: string | null;
      configContract?: string | null;
      infoLink?: string | null;
      message?: components["schemas"]["ProviderMessage"];
      tags?: number[] | null;
      presets?: components["schemas"]["IndexerResource"][] | null;
      indexerUrls?: string[] | null;
      legacyUrls?: string[] | null;
      definitionName?: string | null;
      description?: string | null;
      language?: string | null;
      encoding?: string | null;
      enable?: boolean;
      redirect?: boolean;
      supportsRss?: boolean;
      supportsSearch?: boolean;
      supportsRedirect?: boolean;
      /** Format: int32 */
      appProfileId?: number;
      protocol?: components["schemas"]["DownloadProtocol"];
      privacy?: components["schemas"]["IndexerPrivacy"];
      capabilities?: components["schemas"]["IndexerCapabilityResource"];
      /** Format: int32 */
      priority?: number;
      /** Format: date-time */
      added?: string;
      status?: components["schemas"]["IndexerStatusResource"];
      sortName?: string | null;
    };
    IndexerStatistics: {
      /** Format: int32 */
      indexerId?: number;
      indexerName?: string | null;
      /** Format: int32 */
      averageResponseTime?: number;
      /** Format: int32 */
      numberOfQueries?: number;
      /** Format: int32 */
      numberOfGrabs?: number;
      /** Format: int32 */
      numberOfRssQueries?: number;
      /** Format: int32 */
      numberOfAuthQueries?: number;
      /** Format: int32 */
      numberOfFailedQueries?: number;
      /** Format: int32 */
      numberOfFailedGrabs?: number;
      /** Format: int32 */
      numberOfFailedRssQueries?: number;
      /** Format: int32 */
      numberOfFailedAuthQueries?: number;
    };
    IndexerStatsResource: {
      /** Format: int32 */
      id?: number;
      indexers?: components["schemas"]["IndexerStatistics"][] | null;
      userAgents?: components["schemas"]["UserAgentStatistics"][] | null;
      hosts?: components["schemas"]["HostStatistics"][] | null;
    };
    IndexerStatusResource: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      indexerId?: number;
      /** Format: date-time */
      disabledTill?: string | null;
    };
    LanguageResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      nameLower?: string | null;
    };
    LogFileResource: {
      /** Format: int32 */
      id?: number;
      filename?: string | null;
      /** Format: date-time */
      lastWriteTime?: string;
      contentsUrl?: string | null;
      downloadUrl?: string | null;
    };
    LogResource: {
      /** Format: int32 */
      id?: number;
      /** Format: date-time */
      time?: string;
      exception?: string | null;
      exceptionType?: string | null;
      level?: string | null;
      logger?: string | null;
      message?: string | null;
      method?: string | null;
    };
    LogResourcePagingResource: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      sortKey?: string | null;
      sortDirection?: components["schemas"]["SortDirection"];
      filters?: components["schemas"]["PagingResourceFilter"][] | null;
      /** Format: int32 */
      totalRecords?: number;
      records?: components["schemas"]["LogResource"][] | null;
    };
    /** @enum {string} */
    MovieSearchParam:
      | "q"
      | "imdbId"
      | "tmdbId"
      | "imdbTitle"
      | "imdbYear"
      | "traktId"
      | "genre";
    /** @enum {string} */
    MusicSearchParam: "q" | "album" | "artist" | "label" | "year" | "genre";
    NotificationResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      fields?: components["schemas"]["Field"][] | null;
      implementationName?: string | null;
      implementation?: string | null;
      configContract?: string | null;
      infoLink?: string | null;
      message?: components["schemas"]["ProviderMessage"];
      tags?: number[] | null;
      presets?: components["schemas"]["NotificationResource"][] | null;
      link?: string | null;
      onHealthIssue?: boolean;
      onApplicationUpdate?: boolean;
      supportsOnHealthIssue?: boolean;
      includeHealthWarnings?: boolean;
      supportsOnApplicationUpdate?: boolean;
      testCommand?: string | null;
    };
    PagingResourceFilter: {
      key?: string | null;
      value?: string | null;
    };
    ProviderMessage: {
      message?: string | null;
      type?: components["schemas"]["ProviderMessageType"];
    };
    /** @enum {string} */
    ProviderMessageType: "info" | "warning" | "error";
    /** @enum {string} */
    ProxyType: "http" | "socks4" | "socks5";
    ReleaseResource: {
      /** Format: int32 */
      id?: number;
      guid?: string | null;
      /** Format: int32 */
      age?: number;
      /** Format: double */
      ageHours?: number;
      /** Format: double */
      ageMinutes?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int32 */
      files?: number | null;
      /** Format: int32 */
      grabs?: number | null;
      /** Format: int32 */
      indexerId?: number;
      indexer?: string | null;
      subGroup?: string | null;
      releaseHash?: string | null;
      title?: string | null;
      approved?: boolean;
      /** Format: int32 */
      imdbId?: number;
      /** Format: date-time */
      publishDate?: string;
      commentUrl?: string | null;
      downloadUrl?: string | null;
      infoUrl?: string | null;
      posterUrl?: string | null;
      indexerFlags?: string[] | null;
      categories?: components["schemas"]["IndexerCategory"][] | null;
      magnetUrl?: string | null;
      infoHash?: string | null;
      /** Format: int32 */
      seeders?: number | null;
      /** Format: int32 */
      leechers?: number | null;
      protocol?: components["schemas"]["DownloadProtocol"];
    };
    /** @enum {string} */
    SearchParam: "q";
    SelectOption: {
      /** Format: int32 */
      value?: number;
      name?: string | null;
      /** Format: int32 */
      order?: number;
      hint?: string | null;
      /** Format: int32 */
      parentValue?: number | null;
    };
    /** @enum {string} */
    SortDirection: "default" | "ascending" | "descending";
    TagDetailsResource: {
      /** Format: int32 */
      id?: number;
      label?: string | null;
      notificationIds?: number[] | null;
      indexerIds?: number[] | null;
      indexerProxyIds?: number[] | null;
    };
    TagResource: {
      /** Format: int32 */
      id?: number;
      label?: string | null;
    };
    TaskResource: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      taskName?: string | null;
      /** Format: int32 */
      interval?: number;
      /** Format: date-time */
      lastExecution?: string;
      /** Format: date-time */
      lastStartTime?: string;
      /** Format: date-time */
      nextExecution?: string;
      lastDuration?: components["schemas"]["TimeSpan"];
    };
    TimeSpan: {
      /** Format: int64 */
      ticks?: number;
      /** Format: int32 */
      days?: number;
      /** Format: int32 */
      hours?: number;
      /** Format: int32 */
      milliseconds?: number;
      /** Format: int32 */
      minutes?: number;
      /** Format: int32 */
      seconds?: number;
      /** Format: double */
      totalDays?: number;
      /** Format: double */
      totalHours?: number;
      /** Format: double */
      totalMilliseconds?: number;
      /** Format: double */
      totalMinutes?: number;
      /** Format: double */
      totalSeconds?: number;
    };
    /** @enum {string} */
    TvSearchParam:
      | "q"
      | "season"
      | "ep"
      | "imdbId"
      | "tvdbId"
      | "rId"
      | "tvMazeId"
      | "traktId"
      | "tmdbId";
    UiConfigResource: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      firstDayOfWeek?: number;
      calendarWeekColumnHeader?: string | null;
      shortDateFormat?: string | null;
      longDateFormat?: string | null;
      timeFormat?: string | null;
      showRelativeDates?: boolean;
      enableColorImpairedMode?: boolean;
      /** Format: int32 */
      uiLanguage?: number;
      theme?: string | null;
    };
    UpdateChanges: {
      new?: string[] | null;
      fixed?: string[] | null;
    };
    /** @enum {string} */
    UpdateMechanism: "builtIn" | "script" | "external" | "apt" | "docker";
    UpdateResource: {
      /** Format: int32 */
      id?: number;
      version?: components["schemas"]["Version"];
      branch?: string | null;
      /** Format: date-time */
      releaseDate?: string;
      fileName?: string | null;
      url?: string | null;
      installed?: boolean;
      /** Format: date-time */
      installedOn?: string | null;
      installable?: boolean;
      latest?: boolean;
      changes?: components["schemas"]["UpdateChanges"];
      hash?: string | null;
    };
    UserAgentStatistics: {
      userAgent?: string | null;
      /** Format: int32 */
      numberOfQueries?: number;
      /** Format: int32 */
      numberOfGrabs?: number;
    };
    Version: {
      /** Format: int32 */
      major?: number;
      /** Format: int32 */
      minor?: number;
      /** Format: int32 */
      build?: number;
      /** Format: int32 */
      revision?: number;
      /** Format: int32 */
      majorRevision?: number;
      /** Format: int32 */
      minorRevision?: number;
    };
  };
}

export interface operations {
  getApplicationById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ApplicationResource"];
          "application/json": components["schemas"]["ApplicationResource"];
          "text/json": components["schemas"]["ApplicationResource"];
        };
      };
    };
  };
  createApplication: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Success */
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationResource"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationResource"];
        "text/json": components["schemas"]["ApplicationResource"];
        "application/*+json": components["schemas"]["ApplicationResource"];
      };
    };
  };
  deleteApplicationById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Success */
      200: unknown;
    };
  };
  getApplications: {
    responses: {
      /** Success */
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationResource"][];
        };
      };
    };
  };
  updateApplications: {
    responses: {
      /** Success */
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationResource"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationResource"];
        "text/json": components["schemas"]["ApplicationResource"];
        "application/*+json": components["schemas"]["ApplicationResource"];
      };
    };
  };
  getApplicationSchema: {
    responses: {
      /** Success */
      200: {
        content: {
          "application/json": components["schemas"]["ApplicationResource"][];
        };
      };
    };
  };
  testApplication: {
    responses: {
      /** Success */
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationResource"];
        "text/json": components["schemas"]["ApplicationResource"];
        "application/*+json": components["schemas"]["ApplicationResource"];
      };
    };
  };
  testApplications: {
    responses: {
      /** Success */
      200: unknown;
    };
  };
  doApplicationAction: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** Success */
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationResource"];
        "text/json": components["schemas"]["ApplicationResource"];
        "application/*+json": components["schemas"]["ApplicationResource"];
      };
    };
  };
}

export interface external {}
