# syntax=docker/dockerfile:1

FROM node:16-alpine3.14 as base

WORKDIR ./app
ENV NODE_ENV=development

COPY ["*.json", "./"]
RUN npm install -g npm@8
RUN npm install --development

COPY ["*.js", "*.cjs", ".*.*", "./"]
COPY ["src/", "./src/"]
COPY ["test/", "./test/"]
